backend:
  name: github
  repo: fengliteam/schale
  branch: main
  base_url: https://www.xingying.us.kg
  auth_endpoint: /api/auth

media_folder: "public/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "blog"
    label: "📄 博客文章"
    label_singular: "文章"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"
    preview_path: "article/{{slug}}"
    fields:
      - { name: "title", label: "文章标题", widget: "string" }
      - { name: "date", label: "发布日期", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false }
      - { name: "updated", label: "更新日期", widget: "datetime", required: false, date_format: "YYYY-MM-DD", time_format: false }
      - { name: "categories", label: "分类", widget: "string", required: false }
      - { name: "tags", label: "标签", widget: "list", required: false }
      - { name: "cover", label: "封面图", widget: "image", required: false }
      - { name: "recommend", label: "⭐ 推荐文章", widget: "boolean", default: false }
      - { name: "top", label: "📌 置顶文章", widget: "boolean", default: false }
      - { name: "hide", label: "🙈 隐藏文章", widget: "boolean", default: false }
      - { name: "type", label: "页面类型", widget: "select", options: [{ label: "普通文章", value: "" }, { label: "友链页", value: "links" }], default: "" }
      - { name: "comment", label: "开启评论", widget: "boolean", default: true }
      - { name: "body", label: "正文内容", widget: "markdown" }
    sortable_fields: ["date", "title"]
    default_sort: ["date", "desc"]
    view_filters:
      - { label: "全部文章", field: "hide", pattern: false }
      - { label: "已隐藏", field: "hide", pattern: true }
      - { label: "置顶文章", field: "top", pattern: true }
      - { label: "推荐文章", field: "recommend", pattern: true }